### ISSUE TITLE
Can I become a part of the project?

### ISSUE THREAD

**Issue by shivanshsinghx365** [LinuxKits/Distro-wallpapers#12]
### Hello everyone,
I recently stumbled upon your project after seeing it on Nazib's profile
I am genuinely interested in the project
**If you guys have no issues, then can i be a part of the project?** 

Additionally I have just created a pull request in which I have updated wallpaper catalogue for Ubuntu and Linux mint, please do review that and merge it.

Thank you

**Comment by happyeggchen** [comment]
Do you have a discord or telegram?
