### ISSUE TITLE
can you add mint 21 vanessa wallpapers? 

### ISSUE THREAD

**Issue by pakair** [LinuxKits/Distro-wallpapers#22]
there are 22.

**Comment by happyeggchen** [comment]
my laptop is not available now since i'm in school...
Could you please open a pull request for this?
I'll merge it

**Comment by pakair** [comment]
I have to admit, I don't know how to do a pull request. 
But ... I added those wallpapers in my github page. https://github.com/pakair/Linuxmint-21-vanessa
They are public so you should be able to cp them and update your repo.

**Comment by shivanshsinghx365** [comment]
@pakair & @happyeggchen don't worry, I will create the PR

**Comment by shivanshsinghx365** [comment]
Done, Linux mint 21-vanessa wallpapers have been added
Will add linux mint 22 wallpapers after some time
after that the issue will be closed

**Comment by shivanshsinghx365** [comment]
Linux mint 21 Vanessa wallpapers have been added
I am now closing the issue
Thanks for the wallpapers @pakair :+1:
